// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address_req.proto

package netpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddrReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddrReq) Reset()         { *m = AddrReq{} }
func (m *AddrReq) String() string { return proto.CompactTextString(m) }
func (*AddrReq) ProtoMessage()    {}
func (*AddrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_req_611796d3afcf09a1, []int{0}
}
func (m *AddrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddrReq.Unmarshal(m, b)
}
func (m *AddrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddrReq.Marshal(b, m, deterministic)
}
func (dst *AddrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddrReq.Merge(dst, src)
}
func (m *AddrReq) XXX_Size() int {
	return xxx_messageInfo_AddrReq.Size(m)
}
func (m *AddrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddrReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddrReq proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddrReq)(nil), "netpb.AddrReq")
}

func init() { proto.RegisterFile("address_req.proto", fileDescriptor_address_req_611796d3afcf09a1) }

var fileDescriptor_address_req_611796d3afcf09a1 = []byte{
	// 66 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4c, 0x49, 0x29,
	0x4a, 0x2d, 0x2e, 0x8e, 0x2f, 0x4a, 0x2d, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd,
	0x4b, 0x2d, 0x29, 0x48, 0x52, 0xe2, 0xe4, 0x62, 0x77, 0x4c, 0x49, 0x29, 0x0a, 0x4a, 0x2d, 0x4c,
	0x62, 0x03, 0x4b, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x68, 0x91, 0x99, 0x1e, 0x2d, 0x00,
	0x00, 0x00,
}
