// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address.proto

/*
Package netpb is a generated protocol buffer package.

It is generated from these files:
	address.proto
	address_req.proto
	block_header.proto
	block_headers_req.proto
	block.proto
	blocks_req.proto
	consensus.proto
	data_req.proto
	dht_pingpong.proto
	disconnected.proto
	findnode.proto
	inventory.proto
	neighbors.proto
	notfound.proto
	ping.proto
	pong.proto
	transaction.proto
	verack.proto
	version.proto
	block_header.proto

It has these top-level messages:
	PeerAddr
	Addrs
	AddrReq
	Header
	BlkHeader
	HeadersReq
	Block
	BlocksReq
	ConsensusPayload
	Consensus
	DataReq
	EndPoint
	DHTPing
	DHTPong
	Disconnected
	FindNode
	InvPayload
	Inv
	Node
	Neighbors
	NotFound
	Ping
	Pong
	Sig
	Transaction
	Trn
	VerAck
	VersionPayload
	Version
	Header
	BlkHeader
*/
package netpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerAddr struct {
	Time          int64  `protobuf:"varint,1,opt,name=Time" json:"Time,omitempty"`
	Services      uint64 `protobuf:"varint,2,opt,name=Services" json:"Services,omitempty"`
	IpAddr        []byte `protobuf:"bytes,3,opt,name=IpAddr,proto3" json:"IpAddr,omitempty"`
	Port          uint32 `protobuf:"varint,4,opt,name=Port" json:"Port,omitempty"`
	ConsensusPort uint32 `protobuf:"varint,5,opt,name=ConsensusPort" json:"ConsensusPort,omitempty"`
	ID            uint64 `protobuf:"varint,6,opt,name=ID" json:"ID,omitempty"`
}

func (m *PeerAddr) Reset()                    { *m = PeerAddr{} }
func (m *PeerAddr) String() string            { return proto.CompactTextString(m) }
func (*PeerAddr) ProtoMessage()               {}
func (*PeerAddr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PeerAddr) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PeerAddr) GetServices() uint64 {
	if m != nil {
		return m.Services
	}
	return 0
}

func (m *PeerAddr) GetIpAddr() []byte {
	if m != nil {
		return m.IpAddr
	}
	return nil
}

func (m *PeerAddr) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PeerAddr) GetConsensusPort() uint32 {
	if m != nil {
		return m.ConsensusPort
	}
	return 0
}

func (m *PeerAddr) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type Addrs struct {
	NodeAddrs []*PeerAddr `protobuf:"bytes,1,rep,name=NodeAddrs" json:"NodeAddrs,omitempty"`
}

func (m *Addrs) Reset()                    { *m = Addrs{} }
func (m *Addrs) String() string            { return proto.CompactTextString(m) }
func (*Addrs) ProtoMessage()               {}
func (*Addrs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Addrs) GetNodeAddrs() []*PeerAddr {
	if m != nil {
		return m.NodeAddrs
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerAddr)(nil), "netpb.PeerAddr")
	proto.RegisterType((*Addrs)(nil), "netpb.Addrs")
}

func init() { proto.RegisterFile("address.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x49, 0x29,
	0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4b, 0x2d, 0x29, 0x48,
	0x52, 0x9a, 0xc3, 0xc8, 0xc5, 0x11, 0x90, 0x9a, 0x5a, 0xe4, 0x98, 0x92, 0x52, 0x24, 0x24, 0xc4,
	0xc5, 0x12, 0x92, 0x99, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0x66, 0x0b, 0x49,
	0x71, 0x71, 0x04, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x16, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0xb0,
	0x04, 0xc1, 0xf9, 0x42, 0x62, 0x5c, 0x6c, 0x9e, 0x05, 0x20, 0x9d, 0x12, 0xcc, 0x0a, 0x8c, 0x1a,
	0x3c, 0x41, 0x50, 0x1e, 0xc8, 0x9c, 0x80, 0xfc, 0xa2, 0x12, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xde,
	0x20, 0x30, 0x5b, 0x48, 0x85, 0x8b, 0xd7, 0x39, 0x3f, 0xaf, 0x38, 0x35, 0xaf, 0xb8, 0xb4, 0x18,
	0x2c, 0xc9, 0x0a, 0x96, 0x44, 0x15, 0x14, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x03, 0xdb,
	0xc3, 0xe4, 0xe9, 0xa2, 0x64, 0xc6, 0xc5, 0x0a, 0x32, 0xb1, 0x58, 0x48, 0x97, 0x8b, 0xd3, 0x2f,
	0x3f, 0x25, 0x15, 0xcc, 0x91, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0xd7, 0x03, 0x7b, 0x41,
	0x0f, 0xe6, 0xfc, 0x20, 0x84, 0x8a, 0x24, 0x36, 0xb0, 0x27, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x1d, 0x88, 0x85, 0x44, 0xf5, 0x00, 0x00, 0x00,
}
