// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blocks_req.proto

package netpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlocksReq struct {
	HeaderHashCount      uint32   `protobuf:"varint,1,opt,name=HeaderHashCount,proto3" json:"HeaderHashCount,omitempty"`
	HashStart            []byte   `protobuf:"bytes,2,opt,name=HashStart,proto3" json:"HashStart,omitempty"`
	HashStop             []byte   `protobuf:"bytes,3,opt,name=HashStop,proto3" json:"HashStop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlocksReq) Reset()         { *m = BlocksReq{} }
func (m *BlocksReq) String() string { return proto.CompactTextString(m) }
func (*BlocksReq) ProtoMessage()    {}
func (*BlocksReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_blocks_req_21fe21bd73b8c344, []int{0}
}
func (m *BlocksReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksReq.Unmarshal(m, b)
}
func (m *BlocksReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksReq.Marshal(b, m, deterministic)
}
func (dst *BlocksReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksReq.Merge(dst, src)
}
func (m *BlocksReq) XXX_Size() int {
	return xxx_messageInfo_BlocksReq.Size(m)
}
func (m *BlocksReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksReq proto.InternalMessageInfo

func (m *BlocksReq) GetHeaderHashCount() uint32 {
	if m != nil {
		return m.HeaderHashCount
	}
	return 0
}

func (m *BlocksReq) GetHashStart() []byte {
	if m != nil {
		return m.HashStart
	}
	return nil
}

func (m *BlocksReq) GetHashStop() []byte {
	if m != nil {
		return m.HashStop
	}
	return nil
}

func init() {
	proto.RegisterType((*BlocksReq)(nil), "netpb.BlocksReq")
}

func init() { proto.RegisterFile("blocks_req.proto", fileDescriptor_blocks_req_21fe21bd73b8c344) }

var fileDescriptor_blocks_req_21fe21bd73b8c344 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xca, 0xc9, 0x4f,
	0xce, 0x2e, 0x8e, 0x2f, 0x4a, 0x2d, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4b,
	0x2d, 0x29, 0x48, 0x52, 0xca, 0xe7, 0xe2, 0x74, 0x02, 0x4b, 0x05, 0xa5, 0x16, 0x0a, 0x69, 0x70,
	0xf1, 0x7b, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x79, 0x24, 0x16, 0x67, 0x38, 0xe7, 0x97, 0xe6, 0x95,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0xa1, 0x0b, 0x0b, 0xc9, 0x70, 0x71, 0x82, 0x38, 0xc1,
	0x25, 0x89, 0x45, 0x25, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x08, 0x01, 0x21, 0x29, 0x2e,
	0x0e, 0x08, 0x27, 0xbf, 0x40, 0x82, 0x19, 0x2c, 0x09, 0xe7, 0x27, 0xb1, 0x81, 0xad, 0x37, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x2a, 0xeb, 0xb2, 0x92, 0x00, 0x00, 0x00,
}
