// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dht_pingpong.proto

package netpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EndPoint struct {
	Addr                 []byte   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	UDPPort              uint32   `protobuf:"varint,2,opt,name=UDPPort,proto3" json:"UDPPort,omitempty"`
	TCPPort              uint32   `protobuf:"varint,3,opt,name=TCPPort,proto3" json:"TCPPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndPoint) Reset()         { *m = EndPoint{} }
func (m *EndPoint) String() string { return proto.CompactTextString(m) }
func (*EndPoint) ProtoMessage()    {}
func (*EndPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_dht_pingpong_da5cf8d09e8d4ef0, []int{0}
}
func (m *EndPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndPoint.Unmarshal(m, b)
}
func (m *EndPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndPoint.Marshal(b, m, deterministic)
}
func (dst *EndPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndPoint.Merge(dst, src)
}
func (m *EndPoint) XXX_Size() int {
	return xxx_messageInfo_EndPoint.Size(m)
}
func (m *EndPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_EndPoint.DiscardUnknown(m)
}

var xxx_messageInfo_EndPoint proto.InternalMessageInfo

func (m *EndPoint) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *EndPoint) GetUDPPort() uint32 {
	if m != nil {
		return m.UDPPort
	}
	return 0
}

func (m *EndPoint) GetTCPPort() uint32 {
	if m != nil {
		return m.TCPPort
	}
	return 0
}

type DHTPing struct {
	Version              uint32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	FromID               []byte    `protobuf:"bytes,2,opt,name=FromID,proto3" json:"FromID,omitempty"`
	SrcEndPoint          *EndPoint `protobuf:"bytes,3,opt,name=SrcEndPoint,proto3" json:"SrcEndPoint,omitempty"`
	DestEndPoint         *EndPoint `protobuf:"bytes,4,opt,name=DestEndPoint,proto3" json:"DestEndPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DHTPing) Reset()         { *m = DHTPing{} }
func (m *DHTPing) String() string { return proto.CompactTextString(m) }
func (*DHTPing) ProtoMessage()    {}
func (*DHTPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_dht_pingpong_da5cf8d09e8d4ef0, []int{1}
}
func (m *DHTPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTPing.Unmarshal(m, b)
}
func (m *DHTPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTPing.Marshal(b, m, deterministic)
}
func (dst *DHTPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTPing.Merge(dst, src)
}
func (m *DHTPing) XXX_Size() int {
	return xxx_messageInfo_DHTPing.Size(m)
}
func (m *DHTPing) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTPing.DiscardUnknown(m)
}

var xxx_messageInfo_DHTPing proto.InternalMessageInfo

func (m *DHTPing) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DHTPing) GetFromID() []byte {
	if m != nil {
		return m.FromID
	}
	return nil
}

func (m *DHTPing) GetSrcEndPoint() *EndPoint {
	if m != nil {
		return m.SrcEndPoint
	}
	return nil
}

func (m *DHTPing) GetDestEndPoint() *EndPoint {
	if m != nil {
		return m.DestEndPoint
	}
	return nil
}

type DHTPong struct {
	Version              uint32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	FromID               []byte    `protobuf:"bytes,2,opt,name=FromID,proto3" json:"FromID,omitempty"`
	SrcEndPoint          *EndPoint `protobuf:"bytes,3,opt,name=SrcEndPoint,proto3" json:"SrcEndPoint,omitempty"`
	DestEndPoint         *EndPoint `protobuf:"bytes,4,opt,name=DestEndPoint,proto3" json:"DestEndPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DHTPong) Reset()         { *m = DHTPong{} }
func (m *DHTPong) String() string { return proto.CompactTextString(m) }
func (*DHTPong) ProtoMessage()    {}
func (*DHTPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_dht_pingpong_da5cf8d09e8d4ef0, []int{2}
}
func (m *DHTPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTPong.Unmarshal(m, b)
}
func (m *DHTPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTPong.Marshal(b, m, deterministic)
}
func (dst *DHTPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTPong.Merge(dst, src)
}
func (m *DHTPong) XXX_Size() int {
	return xxx_messageInfo_DHTPong.Size(m)
}
func (m *DHTPong) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTPong.DiscardUnknown(m)
}

var xxx_messageInfo_DHTPong proto.InternalMessageInfo

func (m *DHTPong) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DHTPong) GetFromID() []byte {
	if m != nil {
		return m.FromID
	}
	return nil
}

func (m *DHTPong) GetSrcEndPoint() *EndPoint {
	if m != nil {
		return m.SrcEndPoint
	}
	return nil
}

func (m *DHTPong) GetDestEndPoint() *EndPoint {
	if m != nil {
		return m.DestEndPoint
	}
	return nil
}

func init() {
	proto.RegisterType((*EndPoint)(nil), "netpb.EndPoint")
	proto.RegisterType((*DHTPing)(nil), "netpb.DHTPing")
	proto.RegisterType((*DHTPong)(nil), "netpb.DHTPong")
}

func init() { proto.RegisterFile("dht_pingpong.proto", fileDescriptor_dht_pingpong_da5cf8d09e8d4ef0) }

var fileDescriptor_dht_pingpong_da5cf8d09e8d4ef0 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xc9, 0x28, 0x89,
	0x2f, 0xc8, 0xcc, 0x4b, 0x2f, 0xc8, 0xcf, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xcd, 0x4b, 0x2d, 0x29, 0x48, 0x52, 0x0a, 0xe2, 0xe2, 0x70, 0xcd, 0x4b, 0x09, 0xc8, 0xcf, 0xcc,
	0x2b, 0x11, 0x12, 0xe2, 0x62, 0x71, 0x4c, 0x49, 0x29, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09,
	0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x43, 0x5d, 0x02, 0x02, 0xf2, 0x8b, 0x4a, 0x24, 0x98, 0x14,
	0x18, 0x35, 0x78, 0x83, 0x60, 0x5c, 0x90, 0x4c, 0x88, 0x33, 0x44, 0x86, 0x19, 0x22, 0x03, 0xe5,
	0x2a, 0x2d, 0x66, 0xe4, 0x62, 0x77, 0xf1, 0x08, 0x09, 0xc8, 0xcc, 0x4b, 0x07, 0xa9, 0x0a, 0x4b,
	0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0x03, 0x1b, 0xcb, 0x1b, 0x04, 0xe3, 0x0a, 0x89, 0x71, 0xb1, 0xb9,
	0x15, 0xe5, 0xe7, 0x7a, 0xba, 0x80, 0x0d, 0xe6, 0x09, 0x82, 0xf2, 0x84, 0x0c, 0xb9, 0xb8, 0x83,
	0x8b, 0x92, 0x61, 0x8e, 0x02, 0x9b, 0xcd, 0x6d, 0xc4, 0xaf, 0x07, 0x76, 0xae, 0x1e, 0x4c, 0x38,
	0x08, 0x59, 0x8d, 0x90, 0x31, 0x17, 0x8f, 0x4b, 0x6a, 0x71, 0x09, 0x5c, 0x0f, 0x0b, 0x76, 0x3d,
	0x28, 0x8a, 0xe0, 0xae, 0xcc, 0x1f, 0xcc, 0xae, 0x4c, 0x62, 0x03, 0xc7, 0x96, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xbf, 0xff, 0xfb, 0x47, 0xc3, 0x01, 0x00, 0x00,
}
