// Code generated by protoc-gen-go. DO NOT EDIT.
// source: version.proto

package netpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionPayload struct {
	Version              uint32   `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Services             uint64   `protobuf:"varint,2,opt,name=Services,proto3" json:"Services,omitempty"`
	TimeStamp            int64    `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	SyncPort             uint32   `protobuf:"varint,4,opt,name=SyncPort,proto3" json:"SyncPort,omitempty"`
	HttpInfoPort         uint32   `protobuf:"varint,5,opt,name=HttpInfoPort,proto3" json:"HttpInfoPort,omitempty"`
	ConsPort             uint32   `protobuf:"varint,6,opt,name=ConsPort,proto3" json:"ConsPort,omitempty"`
	UDPPort              uint32   `protobuf:"varint,7,opt,name=UDPPort,proto3" json:"UDPPort,omitempty"`
	Cap                  []byte   `protobuf:"bytes,8,opt,name=Cap,proto3" json:"Cap,omitempty"`
	Nonce                uint64   `protobuf:"varint,9,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	StartHeight          uint64   `protobuf:"varint,10,opt,name=StartHeight,proto3" json:"StartHeight,omitempty"`
	Relay                uint32   `protobuf:"varint,11,opt,name=Relay,proto3" json:"Relay,omitempty"`
	IsConsensus          bool     `protobuf:"varint,12,opt,name=IsConsensus,proto3" json:"IsConsensus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionPayload) Reset()         { *m = VersionPayload{} }
func (m *VersionPayload) String() string { return proto.CompactTextString(m) }
func (*VersionPayload) ProtoMessage()    {}
func (*VersionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_7485836b320e8601, []int{0}
}
func (m *VersionPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionPayload.Unmarshal(m, b)
}
func (m *VersionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionPayload.Marshal(b, m, deterministic)
}
func (dst *VersionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionPayload.Merge(dst, src)
}
func (m *VersionPayload) XXX_Size() int {
	return xxx_messageInfo_VersionPayload.Size(m)
}
func (m *VersionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_VersionPayload proto.InternalMessageInfo

func (m *VersionPayload) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VersionPayload) GetServices() uint64 {
	if m != nil {
		return m.Services
	}
	return 0
}

func (m *VersionPayload) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *VersionPayload) GetSyncPort() uint32 {
	if m != nil {
		return m.SyncPort
	}
	return 0
}

func (m *VersionPayload) GetHttpInfoPort() uint32 {
	if m != nil {
		return m.HttpInfoPort
	}
	return 0
}

func (m *VersionPayload) GetConsPort() uint32 {
	if m != nil {
		return m.ConsPort
	}
	return 0
}

func (m *VersionPayload) GetUDPPort() uint32 {
	if m != nil {
		return m.UDPPort
	}
	return 0
}

func (m *VersionPayload) GetCap() []byte {
	if m != nil {
		return m.Cap
	}
	return nil
}

func (m *VersionPayload) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *VersionPayload) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *VersionPayload) GetRelay() uint32 {
	if m != nil {
		return m.Relay
	}
	return 0
}

func (m *VersionPayload) GetIsConsensus() bool {
	if m != nil {
		return m.IsConsensus
	}
	return false
}

type Version struct {
	P                    *VersionPayload `protobuf:"bytes,1,opt,name=P,proto3" json:"P,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_7485836b320e8601, []int{1}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetP() *VersionPayload {
	if m != nil {
		return m.P
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionPayload)(nil), "netpb.VersionPayload")
	proto.RegisterType((*Version)(nil), "netpb.Version")
}

func init() { proto.RegisterFile("version.proto", fileDescriptor_version_7485836b320e8601) }

var fileDescriptor_version_7485836b320e8601 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0xc9, 0xba, 0x6e, 0xdd, 0xbf, 0x9d, 0x48, 0x50, 0x08, 0xe2, 0x21, 0xd4, 0x4b, 0x4f,
	0x3d, 0xe8, 0x47, 0x98, 0x87, 0xed, 0x22, 0x25, 0x55, 0xef, 0x59, 0x8d, 0x5a, 0xd8, 0x92, 0xd2,
	0xc4, 0x41, 0xbf, 0xab, 0x1f, 0x46, 0xf2, 0xcf, 0x56, 0xb7, 0x5b, 0x7e, 0xef, 0xf1, 0x92, 0xc7,
	0x0b, 0x2c, 0x0f, 0xaa, 0xb7, 0xad, 0xd1, 0x65, 0xd7, 0x1b, 0x67, 0x68, 0xac, 0x95, 0xeb, 0xb6,
	0xf9, 0xef, 0x04, 0xae, 0xde, 0x83, 0x51, 0xc9, 0x61, 0x67, 0xe4, 0x07, 0x65, 0x30, 0x3f, 0x2a,
	0x8c, 0x70, 0x52, 0x2c, 0xc5, 0x09, 0xe9, 0x1d, 0x24, 0xb5, 0xea, 0x0f, 0x6d, 0xa3, 0x2c, 0x9b,
	0x70, 0x52, 0x4c, 0xc5, 0xc8, 0xf4, 0x1e, 0x16, 0xaf, 0xed, 0x5e, 0xd5, 0x4e, 0xee, 0x3b, 0x16,
	0x71, 0x52, 0x44, 0xe2, 0x5f, 0xc0, 0xe4, 0xa0, 0x9b, 0xca, 0xf4, 0x8e, 0x4d, 0xf1, 0xd2, 0x91,
	0x69, 0x0e, 0xd9, 0xda, 0xb9, 0x6e, 0xa3, 0x3f, 0x0d, 0xfa, 0x31, 0xfa, 0x17, 0x9a, 0xcf, 0xaf,
	0x8c, 0xb6, 0xe8, 0xcf, 0x42, 0xfe, 0xc4, 0xbe, 0xef, 0xdb, 0x73, 0x85, 0xd6, 0x3c, 0xf4, 0x3d,
	0x22, 0xbd, 0x86, 0x68, 0x25, 0x3b, 0x96, 0x70, 0x52, 0x64, 0xc2, 0x1f, 0xe9, 0x0d, 0xc4, 0x2f,
	0x46, 0x37, 0x8a, 0x2d, 0xb0, 0x7e, 0x00, 0xca, 0x21, 0xad, 0x9d, 0xec, 0xdd, 0x5a, 0xb5, 0x5f,
	0xdf, 0x8e, 0x01, 0x7a, 0xe7, 0x92, 0xcf, 0x09, 0xb5, 0x93, 0x03, 0x4b, 0xf1, 0x85, 0x00, 0x3e,
	0xb7, 0xb1, 0xbe, 0x87, 0xd2, 0xf6, 0xc7, 0xb2, 0x8c, 0x93, 0x22, 0x11, 0xe7, 0x52, 0x5e, 0x8e,
	0x5b, 0xd2, 0x07, 0x20, 0x15, 0x0e, 0x9a, 0x3e, 0xde, 0x96, 0x38, 0x7e, 0x79, 0x39, 0xbc, 0x20,
	0xd5, 0x76, 0x86, 0x9f, 0xf3, 0xf4, 0x17, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xc5, 0xad, 0x27, 0xad,
	0x01, 0x00, 0x00,
}
